src/gestao_rh/apps/employees/urls.py
from django.urls import path
from gestao_rh.apps.employees.views import (
    EmployeesList, EmployeesUpdate, EmployeesDelete, EmployeesCreate, Pdf
)

urlpatterns = [
    path('', EmployeesList.as_view(), name='employees-list'),
    path('new/', EmployeesCreate.as_view(), name='employees-create'),
    path('edit/<int:pk>/', EmployeesUpdate.as_view(), name='employees-update'),
    path('delete/<int:pk>/', EmployeesDelete.as_view(), name='employees-delete'),
    path('report/', Pdf.as_view(), name='employees-report'),
]

src/gestao_rh/urls.py
from django.contrib import admin
from django.urls import path, include

from rest_framework import routers
from gestao_rh.apps.employees.api.views import EmployeeViewSet
from gestao_rh.apps.overtime.api.views import OvertimeViewSet
from gestao_rh.apps.core.api.views import CompanyViewSet, DepartmentViewSet

router = routers.DefaultRouter()
router.register('employees', EmployeeViewSet)
router.register('overtimes', OvertimeViewSet)
router.register('departments', DepartmentViewSet)
router.register('companies', CompanyViewSet)

urlpatterns = [
    path('', include('gestao_rh.apps.core.urls')),
    path('employments/', include('gestao_rh.apps.employees.urls')),
    path('documents/', include('gestao_rh.apps.documents.urls')),
    path('overtime/', include('gestao_rh.apps.overtime.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/', include(router.urls)),
]

src/gestao_rh/apps/documents/models.py
from django.db import models
from django.urls import reverse


class Document(models.Model):
    description = models.CharField(max_length=255)
    filename = models.FileField(upload_to='documents')
    owner = models.ForeignKey('employees.Employee',
                              on_delete=models.PROTECT)

    def get_absolute_url(self):
        return reverse('employees-update', args=[self.owner.id])

    def __str__(self):
        return self.description

src/gestao_rh/apps/employees/models.py
from django.db import models
from django.contrib.auth.models import User


class Employee(models.Model):
    STATUS = (
        (1, 'Enabled'),
        (0, 'Disabled')
    )
    name = models.CharField(max_length=100)
    job_title = models.CharField(max_length=100)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    departments = models.ManyToManyField('core.Department',
                                         related_name='employee',
                                         blank=True)
    company = models.ForeignKey('core.Company',
                                on_delete=models.SET_NULL,
                                null=True, blank=True)
    on_vacation = models.BooleanField()
    status = models.PositiveSmallIntegerField(choices=STATUS, default=1)
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    @property
    def overtime_total(self):
        return self.overtime_set.annotate(
            interval=models.ExpressionWrapper(
                models.F('ends') - models.F('starts'), output_field=models.DateTimeField()
            )
        ).aggregate(models.Sum('interval')).get('interval__sum')

    def __str__(self):
        return self.name

src/gestao_rh/apps/overtime/models.py
from django.db import models
from django.urls import reverse


class Overtime(models.Model):
    reason = models.CharField(max_length=80)
    employee = models.ForeignKey('employees.Employee', related_name='employee',
                                 on_delete=models.CASCADE)
    starts = models.DateTimeField()
    ends = models.DateTimeField()

    @property
    def get_interval(self):
        return self.ends - self.starts

    def get_absolute_url(self):
        return reverse('employees-update', args=[self.employee.id])

    def __str__(self):
        return self.reason

src/gestao_rh/apps/employees/api/views.py
from rest_framework import viewsets

from gestao_rh.apps.employees.models import Employee
from gestao_rh.apps.employees.api.serializers import EmployeeSerializer


class EmployeeViewSet(viewsets.ModelViewSet):
    queryset = Employee.objects.all()
    serializer_class = EmployeeSerializer

src/gestao_rh/apps/employees/views.py
import io
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from django.views.generic import ListView
from django.views.generic.base import View
from django.views.generic.edit import (
    UpdateView, DeleteView, CreateView
)

from django.http import HttpResponse
from django.template.loader import get_template
from xhtml2pdf import pisa

from gestao_rh.apps.employees.models import Employee


class EmployeesList(ListView):
    model = Employee

    def get_queryset(self):
        current_company = self.request.user.employee.company
        return Employee.objects.filter(company=current_company)


class EmployeesUpdate(UpdateView):
    model = Employee
    fields = ['name', 'job_title', 'departments',
              'on_vacation', 'status']
    success_url = reverse_lazy('employees-list')


class EmployeesDelete(DeleteView):
    model = Employee
    success_url = reverse_lazy('employees-list')


class EmployeesCreate(CreateView):
    model = Employee
    fields = ['name', 'job_title', 'status']
    success_url = reverse_lazy('employees-list')

    def form_valid(self, form):
        obj = form.save(commit=False)
        user = obj.name.split(' ')
        username = f'{user[0]}.{user[1]}'.lower()
        obj.company = self.request.user.employee.company
        obj.user = User.objects.create(username=username)
        obj.on_vacation = False
        obj.save()
        return super(EmployeesCreate, self).form_valid(form)


class Render:
    @staticmethod
    def render(path: str, params: dict, filename: str):
        template = get_template(path)
        html = template.render(params)
        response = io.BytesIO()
        pdf = pisa.pisaDocument(io.BytesIO(html.encode("UTF-8")), response)
        if not pdf.err:
            response = HttpResponse(
                response.getvalue(), content_type='application/pdf')
            response['Content-Disposition'] = f'attachment;filename={filename}.pdf'
            return response
        else:
            return HttpResponse("error rendering PDF", status=400)


class Pdf(View):
    def get(self, request):
        params = {
            'today': 'Variavel today',
            'sales': 'Variavel sales',
            'request': request
        }
        return Render.render('employees/reports.html', params, 'report')

src/gestao_rh/apps/employees/templates/employees/employee_confirm_delete.html
{% extends 'core/index.html' %}

{% block body %}
<div class="mt-3">
    <form method="POST">
        {% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <input type="submit" class="btn btn-danger" value="Confirm">
    </form>
</div>
{% endblock %}

src/gestao_rh/apps/employees/templates/employees/employee_form.html
{% extends 'core/index.html' %}
{% load bootstrap %}
{% block body %}
<div class="mt-3">
    <div class="user-form">
        <h2>User Information</h2>
        <form  class="form-horizontal" method="POST">
            {% csrf_token %}
            {{ form|bootstrap }}
            <button type="submit" class="btn btn-primary">Salvar</button>
        </form>
    </div>
    <div class="btn-add-document mt-3 mb-3">
        <a href="{% url 'documents-create' object.id %}">
        <button type="submit" class="btn btn-primary">Add Document</button>
        </a>
    </div>
    <div class="documents-list mt-3">
        <h3>Documents</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>Document</th>
                    <th>Options</th>
                </tr>
            </thead>
            <tbody>
                {% for document in object.document_set.all %}
                <tr>
                    <td><a href="{{ document.filename.url }}">{{ document }}</a></td>
                    <td><a href="{% url 'documents-delete' document.id %}">Delete</a></td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="overtime-list mt-3">
    <h3>Overtime</h3>
    <table class="table">
    <thead>
            <tr>
                <th scope="col">Employee</th>
                <th scope="col">Reason</th>
                <th scope="col">Starts</th>
                <th scope="col">Ends</th>
                <th scope="col">Options</th>
            </tr>
        </thead>
        <tbody>
            {% for overtime in object.overtime_set.all %}
            <tr>
                <td>{{ overtime.employee.name }}</td>
                <td>{{ overtime.reason }}</td>
                <td>{{ overtime.starts }}</td>
                <td>{{ overtime.ends }}</td>
                <td><a href="{% url 'overtime-update' overtime.id %}">Edit</a> | <a href="{% url 'overtime-delete' overtime.id %}">Delete</a></td>
            </tr>
            {% endfor %}
        </tbody>
        <tfoot>
            <tr>
                <td>Total</td>
                <td></td>
                <td></td>
                <td>{{ object.overtime_total }}</td>
                <td></td>
            </tr>
        </tfoot>
    </table>
</div>
</div>
{% endblock %}

src/gestao_rh/apps/employees/templates/employees/employee_list.html
{% extends 'core/index.html' %}

{% block body %}
<div class="mt-3">
<table class="table table-striped">
    <thead>
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Job Title</th>
            <th scope="col">Department</th>
            <th scope="col">Company</th>
            <th scope="col">Options</th>
        </tr>
    </thead>
    <tbody>
        {% for employee in object_list %}
        <tr>
            <td>{{ employee.name }}</td>
            <td>{{ employee.job_title }}</td>
            <td>{{ employee.departments.last }}</td>
            <td>{{ employee.company.name }}</td>
            <td><a href="{% url 'employees-update' employee.id %}">Edit</a> | <a href="{% url 'employees-delete' employee.id %}">Delete</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<div>
    <a class="btn btn-info" href="{% url 'employees-create' %}">Add user</a>
    <a class="btn btn-primary" href="{% url 'employees-report' %}">Employees Report</a>
</div>
</div>
{% endblock %}

src/gestao_rh/apps/employees/templates/employees/reports.html
{% extends 'core/index.html' %}

{% block body %}
    <h1>Employees Report</h1>
    <h2>{{ sales }}</h2>
{% endblock %}